### ISSUE TITLE
fillOnblur=true may not pick best match when Enter is pressed

### ISSUE THREAD

**Issue by gjsjohnmurray** [ivkremer/jquery-simple-combobox#25]
When fillOnBlur is true, if what I type matches more than one entry but matches one of them exactly, when I press Enter you select the first match rather than the exact match. 

To see this, run the fiddle at http://jsfiddle.net/3gpfkgsr/1/

Delete the initial value, type AB, then press Enter. The value filled is ABC rather than AB. This is unexpected.

**Comment by gjsjohnmurray** [comment]
'blur' handler code change that I described at the top of my previous comment (15 Dec 2014) was the #35 merge that fixed #32 today.

**Comment by ivkremer** [comment]
Thanks, I think this is actually the best decision can be made and implemented by now.

**Comment by gjsjohnmurray** [comment]
The relatedTarget fix in pull #35 had to be revised in pull #48 to work on Chrome. The #48 solution has caused issue #63, and to fix that I am going to propose deferring less (but not none) of the blur logic to the timer.

The blur handler already treats the option combination {fillOnBlur: true, invalidAsValue: false} as a special case. When #48 was merged this combination no longer prevented normal selection of list entries on Chrome, because the logic handling it was deferred to the timer. But it's not clear to me what the purpose of the logic is. For the fix to #63 I must either retain that logic in what the timer runs (so it could happen after the click event on a submit button), or we could remove the logic entirely.

I propose removing deprecating the fillOnBlur option and removing its code from the blur handler. Alternatively we could deprecate but not remove the code. Or we could leave the option undeprecated, and maybe someone else will be able to fix it without breaking other stuff.
