### ISSUE TITLE
Change listener returns value before change

### ISSUE THREAD

**Issue by fibericon** [ivkremer/jquery-simple-combobox#32]
Whether you attempt to get the value via this, event, or .('val'), any attempt to get the value of the combobox using the 'change' listener will invariably return the value that the combobox had -before- changing, which makes the data returned not useful in many applications.

**Comment by gjsjohnmurray** [comment]
Demonstrated by http://jsfiddle.net/gjsjohnmurray/61dehy1v/

I have just submitted a pull request with a fix.

**Comment by ivkremer** [comment]
@gjsjohnmurray thank you, very helpful fix.
