### ISSUE TITLE
List drops down when pressing edit navigation keys

### ISSUE THREAD

**Issue by gjsjohnmurray** [ivkremer/jquery-simple-combobox#38]
When the dropdown list is not showing, and focus is in the filter input field, pressing cursor-left reveals the list. In my opinion this is incorrect. Of keystrokes that do not alter the filter value, only the cursor-down key should reveal the list.

I will submit a fix soon.

**Comment by ivkremer** [comment]
I'm fully agree with you, thank you very much for fixing this.
