### ISSUE TITLE
'blur' handler code not working correctly in Chrome 40

### ISSUE THREAD

**Issue by gjsjohnmurray** [ivkremer/jquery-simple-combobox#47]
'blur' handler code change that I described at the top of my 15 Dec 2014 on issue #25 was part of the #35 merge that fixed #32. I'm pretty sure it was working correctly for me in Chrome at that time, but today with Chrome 40 I still have the problem. the relatedElement property of the event is frequently null, even when the new focus element is an item on the list.

I have devised an alternative solution and will submit it for merge soon. Shall wait a while first to see if you merge my previous pull request, #46.

**Comment by ivkremer** [comment]
Yeah, thank you very much, John. I've merged it.
