### ISSUE TITLE
Pressing Escape to close combo also closes window

### ISSUE THREAD

**Issue by gjsjohnmurray** [ivkremer/jquery-simple-combobox#49]
In my app a window acts like a dialog, with OK and Cancel buttons. Escape key is treated as a shortcut for Cancel. When focused on a dropped-down scombobox the Escape key slides the list up as designed, but then propagates and causes my window to close.

I want to stop propagation of Escape when it has just caused the list to slide up, but not when the list was already closed.

I will propose a code change to achieve this. If you don't want to merge it perhaps you can suggest another way to get the result I want. I wondered about using the afterClose callback but (a) I wasn't able to a listener to that, and (b) I don't think the listener will have access to the current event to be able to call its stopPropagation() method.

**Comment by ivkremer** [comment]
@gjsjohnmurray thank you for reporting and fixing. There really should be no propagation.
