### ISSUE TITLE
Attaching beforeOpen, afterOpen, beforeClose, afterClose event code is mis-documented

### ISSUE THREAD

**Issue by gjsjohnmurray** [ivkremer/jquery-simple-combobox#51]
The index.html documentation lists beforeOpen, beforeClose, afterOpen and afterClose as events, to which listeners can be attached in the same way as to change, focus etc, i.e.

$(#id).scombobox('afterClose', function(){})

In fact this give a "No such method" error. Here's an example of how to attach a function to one of these four events:

$(#id).scombobox({afterClose: function(){console.log('afterClose');}});

**Comment by ivkremer** [comment]
Thank you, fixed.

**Comment by gjsjohnmurray** [comment]
I don't see any change in index.html yet.

**Comment by ivkremer** [comment]
I'm sorry, now it is delivered.
