### ISSUE TITLE
Three faults with change event

### ISSUE THREAD

**Issue by gjsjohnmurray** [ivkremer/jquery-simple-combobox#52]
1. Setting a value programmatically raises a change event. This is unexpected, since it is not how a regular SELECT control behaves.

2. Whenever the change event occurs (e.g. user picks a new value) any code attached to the event retrieves the before-change value rather than the after-change one.

3. In some circumstances a single user action produces two change events.

See http://jsfiddle.net/gjsjohnmurray/pw3pL6gc/ for a demonstration of 1 and 2.

I will submit a pull request shortly to fix all three of these faults.

**Comment by ivkremer** [comment]
Thank you very much for reporting and fixing these bugs, very helpful.
