### ISSUE TITLE
When expandOnFocus or expandOnFocusWithValue is false click on dropdown arrow may fail to expand list

### ISSUE THREAD

**Issue by gjsjohnmurray** [ivkremer/jquery-simple-combobox#54]
I will submit a fix shortly.

**Comment by ivkremer** [comment]
Thank you very much for these fixes.

**Comment by gjsjohnmurray** [comment]
Please rebuild the minified version too. And sometime the files at http://kremer.pro/projects/scombobox/ that your fiddles use could perhaps be updated to the latest version.
