### ISSUE TITLE
Keyboard Tab doesn't work when an item matched

### ISSUE THREAD

**Issue by tariqs-repo** [ivkremer/jquery-simple-combobox#66]
If an entered item matches an underlying option, then keyboard Tab key doesn't work.
You can repro it from its jsfiddle #113 (currently the most recent version)
http://jsfiddle.net/user/ivkremer/fiddles/

**Comment by ivkremer** [comment]
@tariqs-repo thanks for reporting.
I suppose there was no need to do `event.preventDefault()`. You can refresh the fiddle.

**Comment by tariqs-repo** [comment]
great. thanks for your quick resolution and response.
