### ISSUE TITLE
can you add delay

### ISSUE THREAD

**Issue by rafalkucharz** [ivkremer/jquery-simple-combobox#69]
Can you add delay in milliseconds between when a keystroke occurs and when a search is performed. For example when you have  list of 1000 elements, now search is start after every letter write (keyup) and performance is very poor (fullMatch). 
I would like to start search immediately after stop writing the word (maybe delay 250ms). 

Second petition, do you considered to use html placehodler <input text... placeholder="please select something..."> when options empty is set to true. Of course text of placeholder shoudl by configurable. 

For both things I modified your plugin for my needs, but code is ugly, anyway if you want to check changes, source are here https://drive.google.com/file/d/0B2naqgtblYdnbmtsQVZMQVRZYkE/view?usp=sharing.

**Comment by ivkremer** [comment]
@rafalkucharz Thanks for suggestions and especially for your coding.
I'll try to implement this feature.

**Comment by ivkremer** [comment]
Thanks once again @rafalkucharz, I've added `filterDelay` option. So your snippet now can be like:
```js
$(element).scombobox({
    filterDelay: 250
});
```

**Comment by rafalkucharz** [comment]
thanks, nice work ;)
