### ISSUE TITLE
Checkbox mode: Cannot read property 'trigger' of undefined

### ISSUE THREAD

**Issue by odie2** [ivkremer/jquery-simple-combobox#72]
Hi,

Why I am sure that is checkbox mode? I tried with

I am using:
```
var createcombos = function() {
   $( "select" ).each( function() {
      if ( ! $( this ).parents( '.scombobox' ).length > 0 ) {
         $( this ).scombobox();
      }
   });
}
```
(BTW maybe is there any better way to don't duplicate select's that already scomboboxed?)
as I call it on init and every time I add new row or table with combobox.

For realize how it's looks in front-end:
![image](https://cloud.githubusercontent.com/assets/9401878/9554446/3a8189e2-4dc6-11e5-97e1-edd21ad2d11a.png)

However I observed that it's broken on init with many instances of checkbox mode's comboboxes:
![image](https://cloud.githubusercontent.com/assets/9401878/9554456/5604b8ba-4dc6-11e5-8379-261eaabe376a.png)

I am not good in JS, but as I understand you follow state of combobox and as I use it on select that every start almost the same (no class or similar): `<select class="combobox" multiple="multiple" name="teachers[1][3][class][]">` (only name is different).

JSFiddle with many instances of select: http://jsfiddle.net/YgeFM/47/
JSFiddle that broken even on only twice instances of multiple select called by tag name with `name` attribute: http://jsfiddle.net/YgeFM/48/

I am using JQuery 1.11.3 (full), JQuery migrate 1.2.1 (minified), scombobox 1.1.21 (oh, I am outdated)
However you could see that it is broken even with resources used in your fiddles.

How can I fast fix it for my own? If I don't fix it in 3 days, I will have to disable plugin until I will find solution.

Thanks in advance,
Greetings

**Comment by ivkremer** [comment]
@odie2 Thank you very much for reporting.
I'm sorry i'm a bit late with a fix but still you can check a solution here http://jsfiddle.net/YgeFM/49/. It was just my bug, there was no need to set a value for a combobox without `selected="selected"` option while initializing it.
Download https://github.com/ivkremer/jquery-simple-combobox/archive/1.1.24.zip this version if you would like to continue using the plugin.

**Comment by odie2** [comment]
Works nice.
Fortunatelly I didn't had to switch plugin off, as until I will instruct target person in few days, so I will be managing script live.

Thanks!
