### ISSUE TITLE
click on the arrow don't hide other selects

### ISSUE THREAD

**Issue by erker** [ivkremer/jquery-simple-combobox#73]
Hi,

if you have opened one combobox and then direcly clicking on the arrow of another combobox the first one won't close the list. By clicking the input it works fine.

![click](https://cloud.githubusercontent.com/assets/14057841/9583399/699e71a8-500b-11e5-9a3c-65e7ed549a65.png)

I've tested it in chrome 44, firefox 40 and IE11 on http://jsfiddle.net/N2scs/171/

thanks and greetings

**Comment by odie2** [comment]
Related #70

**Comment by ivkremer** [comment]
@erker you can try https://github.com/ivkremer/jquery-simple-combobox/releases/tag/1.1.25.

**Comment by erker** [comment]
works fine now. thanks!
