### ISSUE TITLE
Calling scombobox.val() method prior to initialization

### ISSUE THREAD

**Issue by DeanHe** [ivkremer/jquery-simple-combobox#83]
I get the following error:

Unhandled exception at line 4, column 4106 in http://localhost:61864/Script/js/jquery-1.10.1.min.js
0x800a139e - JavaScript runtime error: Calling scombobox.val() method prior to initialization

But I initialize the scombox object in advance already like:
        $(".combo").scombobox({
            highlight: true,
            empty: true
        });
        $("select[name='Reason']").scombobox('val', 'N');

any advice and opinion ? really appreciate .

**Comment by synweap15** [comment]
hey @DeanHe , are you sure that element with name='Reason' has a "combo" class?

**Comment by DeanHe** [comment]
yes, and I find a situation, seem that you can only refer scombobox by id like $("#???"). 
Not working with $("select[name='Reason']").scombobox('val', 'N');
