### ISSUE TITLE
Preventing additional dropdown being added on subsequent init

### ISSUE THREAD

**Issue by mmustala** [ivkremer/jquery-simple-combobox#84]
Hi,

I noticed that if I initialize some select two times with the combobox it generates two input fields. Any subsequent init adds a new input field.

To prevent this I added this code before `methods.init.apply($t);`

```
        if ($t.parent().attr('class') == 'scombobox') {
            // already initialized
            return;
        }
```

I'm initializing the combobox with this

```
  $('select.use_combobox').scombobox({
    highlight: false,
    fullMatch: true,
    removeDuplicates: false
  })
```

**Comment by ivkremer** [comment]
Hi, Mika.
I'm sorry for so late reply. I've add an edit you've suggested here: https://github.com/ivkremer/jquery-simple-combobox/commit/4cce5022be312e087d35698fc6dd039ab738d836.
I suppose I can close this issue if everything is ok now.

**Comment by mmustala** [comment]
Hi.
No problem. You can close the issue. Thanks!

2017-03-13 19:48 GMT+02:00 Ilya Kremer <notifications@github.com>:
